name: bedrock_wiki_cn
description: Bedrock wiki written in simplified Chinese. With context from Bedrock-OSS.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.14
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  xml: ^6.2.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - public/
    - public/assets/images/homepage/
    - public/doc/guide/
    - public/doc/content.xml
